version: "3.7"

services:
  mattermost:
    image: mattermost/mattermost-preview
    volumes:
      - mattermost-data:/mm/mattermost/mattermost-data
      - mmdbdata:/var/lib/mysql
    ports: 
      - 8065:8065
    networks: 
      elastic:
volumes:
  mattermost-data:
    driver: local
  mmdbdata:
    driver: local

networks:
  elastic:
    external: true
    driver: bridge
    
